name=pulp-runtime
version=1.0.0
author=ETH Zurich, University of Bologna, Indonesia Chip Design Collaborative Center (ICDEC)
maintainer=ETH Zurich, University of Bologna, Indonesia Chip Design Collaborative Center (ICDEC)
sentence=Simple runtime for the Pulp (Pulpissimo) architecture.
paragraph=Simple runtime for the Pulp (Pulpissimo) architecture.
#category=Uncategorized
url=http://localhost:8081/
architectures=riscv
includes=pulp.h
#depends=
