#!/bin/sh

# Copyright (C) 2026 Indonesia Chip Design Collaborative Center (ICDEC)
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT.

# script to upload/program riscv elf in single command line
# usage:
#     ./program    <path to toolchain bin> <openocd script> <program elf>
#
# <path to toolchain> is bin directory contain executable
#                     "riscv32-unknown-elf-gdb" and "openocd"
# <openocd script>    is cfg file used as openocd script
#                     (this sh script assume only one openocd script is used and
#                     openocd script is in this sh script directory)
# <program elf>       elf to upload to board
#
# example:
#     ./program    /opt/riscv/bin    soft_pynq-z1.cfg    test.elf

# on error, exit
set -e

# inform this script PID to caller
THIS_SCRIPT_PID="$$"
echo "$0: program/upload elf executable binary to pulpissimo using gdb and openocd"
echo "$0: running with PID: $THIS_SCRIPT_PID"

# argument:
# $1 path to toolchain
# $2 openocd script to be used
# $3 program/elf to upload

if [ "$#" -ne 3 ] ; then
	echo "Error: Illegal number of parameters."
	echo "Usage: $0 <path to toolchain bin> <openocd script> <program elf>"
	echo "example: $0 /opt/riscv/bin pulpissimo_jlink test.elf"
	exit 1
fi

# get directory of this script (sh version maybe not working
# if this sh script directory included in PATH and this sh script
# called like calling system command or without path to this sh script)
export THIS_SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# export path to toolchain
export PATH="$PATH:$1"

# call openocd and send to background
openocd -s "$THIS_SCRIPT_DIR" -f "$2" &

# get openocd PID
OPENOCD_PID="$!"

# wait openocd up
sleep 2

# create gdb script (need mktemp command)
GDB_SCRIPT="$(mktemp)"

cat > "$GDB_SCRIPT" <<EOF
target extended-remote :3333
monitor reset halt
load
monitor resume
monitor shutdown
disconnect
#detach
quit
EOF

# upload with gdb
riscv32-unknown-elf-gdb --command="$GDB_SCRIPT" "$3"

# remove temporary file
rm --verbose "$GDB_SCRIPT"

# wait openocd exit
wait "$OPENOCD_PID"
