#!/bin/sh
# Copyright (C) 2026 Indonesia Chip Design Collaborative Center (ICDEC)
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT.

# get directory of this script (sh version maybe not working
# if this sh script directory included in PATH and this sh script
# called like calling system command or without path to this sh script)
export THIS_SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# since pushd is not available, just use regular cd command
LAST_DIR="$PWD"
cd "$THIS_SCRIPT_DIR"


# NOTE 1: PLEASE MAKE SURE THIS CONFIGURATION IS SAME WITH TESTER FILE
#         (../../spi_flash_writer.c)

# NOTE 2: PLEASE USE DECIMAL NOTATION!

START_WRITE_ADDRESS="0"
#SPI_FLASH_SIZE_BYTES="8388608" # ((64 * 1024 * 1024) / 8) (8 MiB)
SPI_FLASH_SECTOR_SIZE_BYTES="4096" # (4 * 1024)

SPI_FLASH_VERIFY_READ_BLOCK_SIZE_BYTES="$SPI_FLASH_SECTOR_SIZE_BYTES"

# NOTE 1: PLEASE MAKE SURE THIS CONFIGURATION IS SAME WITH TESTER FILE
#         (spi_flash_simulation_posix.h), relative path is to executable
#         which is defined by ../../Makefile
FLASH_FILE="$THIS_SCRIPT_DIR/../../flash_content.bin"



# test, for best TEST result, use number that not divisible by 256 (page size)
TEST_FILE_SIZE="3150033" # ~ 3 MiB


# random source (don't need to be cryptograpically secure)
RANDOM_SOURCE="/dev/urandom"


# build result/test executable
# make sure this align with APP value in ../../Makefile or environment variable
#EXECUTABLE="$THIS_SCRIPT_DIR/../../spi_flash_writer"



# ##################################################
# generate test file

# try to build
make all
RETVAL="$?"
if [ "$RETVAL" -ne "0" ] ; then
	# exit on error
	exit "$RETVAL"
fi


# ##################################################
# prepare files

# file under test
TEST_FILE="$(mktemp)"

# prepare
dd bs="$TEST_FILE_SIZE" count="1" if="$RANDOM_SOURCE" of="$TEST_FILE" conv="nocreat,notrunc"


# create gdbinit file
GDBINIT="$(mktemp)"


# (force) copy test file to flash file, flash file will be truncated by simulation
cp -vf "$TEST_FILE" "$FLASH_FILE"


# create memory dump file
FLASH_VERIFY_FILE="$(mktemp)"


# ##################################################
# create gdbinit file

echo "set pagination off" >> "$GDBINIT"
#echo "target remote | $(which "vgdb")" >> "$GDBINIT"
echo "break INTERRUPT_HERE_TO_READ_DATA_FROM_FLASH" >> "$GDBINIT"
echo "#break INTERRUPT_HERE_TO_FINISH_PROGRAM" >> "$GDBINIT"
echo "run" >> "$GDBINIT"
#echo "continue" >> "$GDBINIT"

i="0"
while [ "$((i * SPI_FLASH_VERIFY_READ_BLOCK_SIZE_BYTES))" -lt "$TEST_FILE_SIZE" ] ; do

	echo "set variable stop_read=0" >> "$GDBINIT"
	echo "append memory $FLASH_VERIFY_FILE buffer buffer+$SPI_FLASH_VERIFY_READ_BLOCK_SIZE_BYTES" >> "$GDBINIT"
	echo "continue" >> "$GDBINIT"
	echo "echo RECEIVED $SPI_FLASH_VERIFY_READ_BLOCK_SIZE_BYTES BYTES DATA FROM FLASH, SEQUENCE $i" >> "$GDBINIT"

	i="$((i + 1))"
done

echo "set variable stop_read=1" >> "$GDBINIT"
echo "disable breakpoints" >> "$GDBINIT"
echo "continue" >> "$GDBINIT"
echo "quit" >> "$GDBINIT"


# ##################################################
# call do debug
GDB_OPT="-x $GDBINIT" make debug

# #################################################
# test simulation result

# check memory dump file size
FLASH_VERIFY_FILE_SIZE="$(wc -c "$FLASH_VERIFY_FILE" | sed -e "s/^\\([0-9]\\+\\)[[:blank:]]\\+.*/\\1/g")"
if [ "$FLASH_VERIFY_FILE_SIZE" -lt "$TEST_FILE_SIZE" ] ; then
	# error because FLASH_VERIFY_FILE_SIZE less than TEST_FILE_SIZE
	# GDBINIT file generation need to be fixed!
	echo "ERROR: FLASH_VERIFY_FILE_SIZE less than TEST_FILE_SIZE!"
	echo "ERROR: fix your GDBINIT file!"

	# cleanup temporary file
	rm "$TEST_FILE" "$FLASH_VERIFY_FILE" "$GDBINIT"

	exit 2
else
	# truncate flash verify file
	dd if="/dev/null" of="$FLASH_VERIFY_FILE" bs=1 count=0 seek="$TEST_FILE_SIZE"

	# check binary
	RETVAL="0"
	cmp "$TEST_FILE" "$FLASH_VERIFY_FILE" || RETVAL="$?" || true
	if [ "$RETVAL" -ne "0" ] ; then
		echo "ERROR: TEST_FILE content don't match with FLASH_VERIFY_FILE"

		# cleanup
		rm "$TEST_FILE" "$FLASH_VERIFY_FILE" "$GDBINIT"

		exit 3
	else
		echo "TEST_FILE and FLASH_VERIFY_FILE content match!"
		echo "TEST PASS!"
	fi
fi


# popd not available
cd "$LAST_DIR"


# ##################################################
# clean up temporary files

# remove list file and merge file
rm "$TEST_FILE" "$FLASH_VERIFY_FILE" "$GDBINIT"
